In [0]:
import nltk 
nltk.download('all')

In [0]:
import numpy as np
from nltk.corpus import stopwords
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
import string
from nltk.corpus import wordnet
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from nltk.tokenize import sent_tokenize,word_tokenize
from sklearn import ensemble
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
import csv
from sklearn.model_selection import cross_val_score

In [7]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 0000000000002747_training_twitter_x_y_train.csv to 0000000000002747_training_twitter_x_y_train.csv
User uploaded file "0000000000002747_training_twitter_x_y_train.csv" with length 2158741 bytes

In [8]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 0000000000002747_test_twitter_x_test.csv to 0000000000002747_test_twitter_x_test.csv
User uploaded file "0000000000002747_test_twitter_x_test.csv" with length 747871 bytes

In [0]:
def loading():
#     data_training=pd.read_csv('G:\Development\Projects\Python Projects\Machine_Learning\\NLP\\NLP_Project\\0000000000002747_training_twitter_x_y_train.csv',header=None)
#     data_test=pd.read_csv('G:\Development\Projects\Python Projects\Machine_Learning\\NLP\\NLP_Project\\0000000000002747_test_twitter_x_test.csv',header=None)
  data_test=pd.read_csv('0000000000002747_test_twitter_x_test.csv',header=None)
  data_training=pd.read_csv('0000000000002747_training_twitter_x_y_train.csv',header=None)
  data_training.columns=['tweet_id',
                           'airline_sentiment',
                           'airline',
                           'airline_sentiment_gold',
                           'name',
                           'negativereason_gold',
                           'retweet_count',
                           'text',
                           'tweet_coord',
                           'tweet_created',
                           'tweet_location',
                           'user_timezone'
                           ]
  data_test.columns =     ['tweet_id',
                             'airline',
                             'airline_sentiment_gold',
                             'name',
                             'negativereason_gold',
                             'retweet_count',
                             'text',
                             'tweet_coord',
                             'tweet_created',
                             'tweet_location',
                             'user_timezone'
                             ]

  return data_training,data_test

In [10]:
data_train,data_test=loading()
y_categories=data_train['airline_sentiment']
del data_train['airline_sentiment']
data_train

,tweet_id,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,tweet_id,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
1,5.679E+17,Southwest,NaN,ColeyGirouard,NaN,0,"@SouthwestAir I am scheduled for the morning, ...",NaN,2/17/2015 20:16,Washington D.C.,Atlantic Time (Canada)
2,5.69989E+17,Southwest,NaN,WalterFaddoul,NaN,0,@SouthwestAir seeing your workers time in and ...,NaN,2/23/2015 14:36,"Indianapolis, Indiana; USA",Central Time (US & Canada)
3,5.68089E+17,United,NaN,LocalKyle,NaN,0,@united Flew ORD to Miami and back and had gr...,NaN,2/18/2015 8:46,Illinois,Central Time (US & Canada)
4,5.68928E+17,Southwest,NaN,amccarthy19,NaN,0,@SouthwestAir @dultch97 that's horse radish 😤🐴,NaN,2/20/2015 16:20,NaN,Atlantic Time (Canada)
5,5.68594E+17,United,NaN,J_Okayy,NaN,0,@united so our flight into ORD was delayed bec...,NaN,2/19/2015 18:13,NaN,Eastern Time (US & Canada)
6,5.69678E+17,United,NaN,bobgiolito,NaN,0,@united Why did you load us in this flying sar...,NaN,2/22/2015 17:58,"Los Angeles, CA",Pacific Time (US & Canada)
7,5.69659E+17,Delta,NaN,aaronkinnari,NaN,0,@JetBlue that is a stock response. Delays not ...,NaN,2/22/2015 16:44,Gotham,Quito
8,5.68543E+17,Delta,NaN,TimothySays,NaN,0,@JetBlue That'd be nice! Hoping to rack up eno...,NaN,2/19/2015 14:48,"Burlington, MA",Eastern Time (US & Canada)
9,5.70116E+17,United,NaN,lindaSWC,NaN,1,@united frankly worse customer service ever. P...,NaN,2/23/2015 23:01,NaN,NaN
10,5.6887E+17,Southwest,NaN,amyums,NaN,0,@SouthwestAir yeah haha. Never been in one. It...,NaN,2/20/2015 12:29,NaN,Central Time (US & Canada)
11,5.67794E+17,Southwest,NaN,Faultie,NaN,0,@SouthwestAir MCO-&gt;DCA flight almost full o...,"[38.73693556, -90.35367062]",2/17/2015 13:12,D.C.,NaN
12,5.69879E+17,Delta,NaN,tonymbove,NaN,0,@JetBlue what's the easiest way to get a ticke...,NaN,2/23/2015 7:20,"Cambridge, MA",Quito
13,5.68518E+17,US Airways,NaN,sherrylweir,NaN,0,@USAirways - love the changes in the lounge - ...,NaN,2/19/2015 13:09,NaN,Quito
14,5.68213E+17,Southwest,NaN,Mselite25,NaN,0,@SouthwestAir I receive bad customer service a...,NaN,2/18/2015 16:58,Rite behind my $$,Mountain Time (US & Canada)
15,5.6927E+17,US Airways,NaN,KennethBracy,NaN,0,@USAirways you're killing me sche a flight to ...,NaN,2/21/2015 14:59,Where ever God puts me,NaN
16,5.67817E+17,US Airways,NaN,SyncSummit,NaN,0,@USAirways 8 weeks to refund this ticket - 037...,NaN,2/17/2015 14:43,Where Music meets Visual Media,Eastern Time (US & Canada)
17,5.6969E+17,American,NaN,Lioninflorida,NaN,0,@AmericanAir no private msg me and will provid...,NaN,2/22/2015 18:48,"Fort Myers, Florida",Eastern Time (US & Canada)
18,5.69933E+17,Delta,NaN,TheBuie,NaN,22,can you not? RT @JetBlue Our fleet's on fleek....,NaN,2/23/2015 10:51,"Raleigh, NC",Eastern Time (US & Canada)
19,5.69939E+17,Delta,NaN,TheRealOx,NaN,0,@JetBlue any info on why flight 704 from SJU t...,NaN,2/23/2015 11:18,NaN,Eastern Time (US & Canada)
20,5.69958E+17,American,NaN,Rizzilient,NaN,0,"@AmericanAir, I've tried no less than 8 times ...",NaN,2/23/2015 12:33,NaN,NaN
21,5.68361E+17,US Airways,NaN,TomFutureforall,NaN,0,@USAirways new problem...had wrong last name o...,NaN,2/19/2015 2:47,NaN,NaN
22,5.68127E+17,Southwest,NaN,DoctorFox007,NaN,0,@SouthwestAir Any possible chance of SWA bring...,NaN,2/18/2015 11:15,"ÜT: 40.819919,-73.864869",Eastern Time (US & Canada)
23,5.68884E+17,US Airways,NaN,chrisseifert83,NaN,0,@USAirways @AmericanAir who runs the show at t...,NaN,2/20/2015 13:24,"Stamford, Ct",Eastern Time (US & Canada)
24,5.70056E+17,United,NaN,JeffPKirkland,NaN,0,@united computers are down but you stopped giv...,NaN,2/23/2015 19:00,Oregon,Pacific Time (US & Canada)
25,5.68804E+17,United,NaN,jonatzzValdez,NaN,0,@united good fly!! #United #businessFirst,"[29.98445184, -95.33224657]",2/20/2015 8:07,Mexico,Central Time (US & Canada)
26,5.67925E+17,United,NaN,MusseZam,NaN,0,"@united I am flying from msp to dxb, my child ...",NaN,2/17/2015 21:54,NaN,NaN
27,5.68434E+17,Delta,NaN,Old_bauer,NaN,0,@JetBlue loves Cancelled Flightling tickets an...,NaN,2/19/2015 7:37,NaN,Eastern Time (US & Canada)
28,5.70083E+17,United,NaN,KeenanPam,NaN,0,"@united In ORD, waited 20 min after crew membe...",NaN,2/23/2015 20:50,NaN,NaN
29,5.68585E+17,Southwest,NaN,Salem_Eways,NaN,0,@SouthwestAir Jason (108639) at Gate #3 in SAN...,NaN,2/19/2015 17:38,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10951,5.69126E+17,Delta,NaN,Dress4YesConJax,NaN,0,@JetBlue Even though this flight #226 didn't h...,NaN,2/21/2015 5:25,NYC,NaN
10952,5.69683E+17,Southwest,NaN,horacioguapo,NaN,0,@SouthwestAir very disappointed in your handli...,NaN,2/22/2015 18:18,NaN,NaN
10953,5.69372E+17,Southwest,NaN,Angela_Meyers,NaN,0,@SouthwestAir flight Cancelled Flightled out o...,NaN,2/21/2015 21:45,"Hershey, PA",Eastern Time (US & Canada)
10954,5.69334E+17,United,NaN,Jo_Frost,NaN,0,@united when I read it say ' in some cases' ca...,NaN,2/21/2015 19:12,Global,Quito
10955,5.68427E+17,Southwest,NaN,thirty_lives,NaN,0,@SouthwestAir you're giving everyone tix for #...,NaN,2/19/2015 7:07,ʞᴚoʎ ʍǝu,Eastern Time (US & Canada)
10956,5.70018E+17,Delta,NaN,4TONEMENT,NaN,0,@JetBlue Am I the only one who had to look tha...,NaN,2/23/2015 16:31,NaN,Eastern Time (US & Canada)
10957,5.68118E+17,Southwest,NaN,BobbiStorm,NaN,0,@SouthwestAir go south everyone,NaN,2/18/2015 10:41,Miami,NaN
10958,5.68523E+17,US Airways,NaN,VirginiaRmz,NaN,0,@USAirways 4 hours Late Flightr And i lost my ...,NaN,2/19/2015 13:29,"Mexico, D.F.",Central Time (US & Canada)
10959,5.70291E+17,United,NaN,nate2482,NaN,0,@united I sure did. I had to drive a total o...,NaN,2/24/2015 10:35,"Parkersburg, WV",Eastern Time (US & Canada)
10960,5.69624E+17,US Airways,NaN,dave_cavan,NaN,0,"@USAirways his name is Rett Cavan, he has a go...","[43.19825137, -70.87335749]",2/22/2015 14:25,"Livonia, MI",NaN
10961,5.68842E+17,United,NaN,iamawarplane,NaN,1,@united 3 times my flight has been delayed and...,NaN,2/20/2015 10:36,"Austin, Texas",NaN
10962,5.69263E+17,Delta,NaN,rosenrj,NaN,0,"@JetBlue there is no supervisor available, so ...",NaN,2/21/2015 14:28,NaN,NaN
10963,5.69308E+17,United,NaN,gwen1013,NaN,0,@united following,NaN,2/21/2015 17:30,"New Haven, CT",NaN
10964,5.69369E+17,US Airways,NaN,dailylaurel,NaN,0,@USAirways even alternate options are allready...,NaN,2/21/2015 21:32,Bruxelle-Paris-Marseille-(BPM),Athens
10965,5.69009E+17,United,NaN,johnwoodRTR,NaN,0,@united Also your at-gate monitor showed 23 em...,"[39.83426941, -104.69960636]",2/20/2015 21:40,Hong Kong,Eastern Time (US & Canada)
10966,5.70165E+17,United,NaN,8629Fissile,NaN,0,@united Okay thank you,NaN,2/24/2015 2:14,NaN,London
10967,5.68417E+17,United,NaN,Brennej,NaN,0,"@united - vacation days: relevant, Ritz in PR ...",NaN,2/19/2015 6:29,NaN,NaN
10968,5.67617E+17,Southwest,NaN,mrshossruns,NaN,0,@SouthwestAir you guys there? Are we on hour 2...,NaN,2/17/2015 1:30,NaN,Eastern Time (US & Canada)
10969,5.69665E+17,American,NaN,vickie_frisbie,NaN,0,@AmericanAir we are through. I can quit you. I...,NaN,2/22/2015 17:07,"Dallas, Texas",Mountain Time (US & Canada)
10970,5.68531E+17,Southwest,NaN,stefughknee,NaN,0,@SouthwestAir thank you! ❤️❤️❤️ you guys!,NaN,2/19/2015 14:02,NaN,NaN
10971,5.70283E+17,Southwest,NaN,slobotski,NaN,0,@SouthwestAir went to purchase a flight that I...,NaN,2/24/2015 10:04,Midwest + Airplanes,Central Time (US & Canada)
10972,5.69087E+17,Delta,NaN,mutantgatto,NaN,0,@JetBlue by any chance do u offer fresh guacam...,NaN,2/21/2015 2:53,ravioli,Eastern Time (US & Canada)
10973,5.70051E+17,US Airways,NaN,m2gris,NaN,0,@USAirways - 53 minutes on hold for a reservat...,NaN,2/23/2015 18:44,"Irvine, Ca",NaN
10974,5.69677E+17,American,NaN,realscooterward,NaN,0,@AmericanAir the worst air experience I have e...,NaN,2/22/2015 17:54,"washington, dc",Eastern Time (US & Canada)
10975,5.69676E+17,Southwest,NaN,happygirlvicki,NaN,0,@SouthwestAir beautiful view flying into San J...,NaN,2/22/2015 17:53,"Omaha, Nebraska",Central Time (US & Canada)
10976,5.69934E+17,American,NaN,Cottopanama85,NaN,0,@AmericanAir followback,NaN,2/23/2015 10:58,"ohio,panama",NaN
10977,5.68564E+17,United,NaN,PaulBEsteves,NaN,0,@united thanks for the help. Wish the phone re...,NaN,2/19/2015 16:13,Brooklyn,Eastern Time (US & Canada)
10978,5.69644E+17,US Airways,NaN,runfixsteve,NaN,0,@usairways the. Worst. Ever. #dca #customerser...,NaN,2/22/2015 15:43,"St. Augustine, Florida",NaN
10979,5.68865E+17,US Airways,NaN,CLChicosky,NaN,0,@nrhodes85: look! Another apology. DO NOT FLY ...,NaN,2/20/2015 12:09,NaN,NaN
10980,5.68929E+17,United,NaN,JW_Blocker,NaN,1,@united you are by far the worst airline. 4 pl...,NaN,2/20/2015 16:24,NaN,NaN

In [0]:
def count_types_output(y):              # This function calculates the different types of
    a=[]                                # outputs that are present in the output column.
    for i in y:                         # eg:- It will calculate and result [0,1](malignant/bennie) for cancer
        if i in a:                      # data set and [0,1](survived/not survived) for the titanic data set.
            continue
        else:
            a.append(i)
    return a


def output_counter(y):                              # This function calculates the number of occurrences of the
    output_label = count_types_output(y)            # different types of outputs present in the output column.
    output_label=np.array(output_label)
    # print(output_label.shape)
    label_count = np.zeros(output_label.shape)
    for i in range(0,len(y)):
        for j in range(len(output_label)):
            if y[i] == output_label[j]:
                label_count[j] = label_count[j] + 1
    # print(label_count)
    dict={}
    for i in range(len(label_count)):
        dict[output_label[i]]=label_count[i]
    return dict

def makeLabelled(column,dict):
    labels=dict.keys()
    new_labels=[i for i in labels]
    # print(new_labels)
    new_column=[]
    for i in range(len(new_labels)):
        if new_labels[i]=='nan':
            nan_index=i
            break
    # print(nan_index)
    column.fillna('nothing',inplace=True)
    for i in range(len(column)):
        if column[i]=='nothing':
            # print(column[i])
            new_column.append(nan_index)
        else:
            for j in range(len(new_labels)):
                if column[i]==new_labels[j]:
                    # print(column[i])
                    new_column.append(j)
                    break
    return new_column

In [0]:

def data_cleaning(data):
    del data['tweet_id']
    del data['name']
    del data['negativereason_gold']
    del data['tweet_created']
    del data['tweet_coord']
    del data['tweet_location']

    dict_airline=(output_counter(data['airline']))
    new_airline=makeLabelled(data['airline'],dict_airline)
    dict_gold_cust = (output_counter(data['airline_sentiment_gold']))
    new_gold_cust=makeLabelled(data['airline_sentiment_gold'],dict_gold_cust)
    dict_timezone=output_counter(data['user_timezone'])
    new_timezone=makeLabelled(data['user_timezone'],dict_timezone)
    return new_airline,new_gold_cust,new_timezone

In [0]:
new_airline_train,new_gold_cust_train,new_timezone_train=data_cleaning(data_train)
new_airline_test,new_gold_cust_test,new_timezone_test=data_cleaning(data_test)

In [0]:

def pos_to_wordnet(pos_tag):
    # print(pos_tag)
    if pos_tag.startswith('J'):
        return wordnet.ADJ
    elif pos_tag.startswith('N'):
        return wordnet.NOUN
    elif pos_tag.startswith('V'):
        return wordnet.VERB
    elif pos_tag.startswith('R'):
        return wordnet.ADJ
    else:
        return wordnet.NOUN


def cleaning_words(words):
    words=word_tokenize(words.lower())
    word_array=[]
    lemmatizer = WordNetLemmatizer()
    stop_words = stopwords.words('english')
    punctuations = list(string.punctuation)
    stop_words += punctuations
    for i in range(len(words)):
        if words[i] in stop_words:
            continue
        else:
            pos_tuple_returned=pos_tag([words[i]])
            word=lemmatizer.lemmatize(words[i],pos=pos_to_wordnet(pos_tuple_returned[0][1]))
            word_array.append(word)
    return word_array


def cleaning_file(document):
    cleaned_words=[]
    for i in range(len(document)):
        new_array=cleaning_words(document[i])
        cleaned_words.append(new_array)
    return cleaned_words

In [0]:

def tweet_cleaning(data):
    text=data['text']
    cleaned_text=cleaning_file(text)
    return cleaned_text

In [0]:
cleaned_text_train=tweet_cleaning(data_train)
cleaned_text_test=tweet_cleaning(data_test)

In [0]:
def creating_sentences(x_y_train):
    x_train_sentences=[]
    for i in range(len(x_y_train)):
        x_train_sentences.append(" ".join(x_y_train[i]))
    return x_train_sentences

In [0]:
x_train_text_sentences=creating_sentences(cleaned_text_train)
x_test_text_sentences=creating_sentences(cleaned_text_test)

In [0]:
def count_vectorize(x_train_sentences,x_test_sentences):
    count_vec=CountVectorizer(max_features=2500,ngram_range=(1,4))
    x_train_features=count_vec.fit_transform(x_train_sentences)
#     print(count_vec.get_feature_names())
    x_train_features=x_train_features.todense()
    x_test_features=count_vec.transform(x_test_sentences)
    x_test_features=x_test_features.todense()
    return x_train_features,x_test_features,count_vec.get_feature_names()

In [0]:
x_train_features,x_test_features,feature_names=count_vectorize(x_train_text_sentences,x_test_text_sentences)

In [0]:
x_train=pd.DataFrame(x_train_features,columns=feature_names)
x_test=pd.DataFrame(x_test_features,columns=feature_names)

In [0]:
x_test['new_airline']=new_airline_test
x_test['new_gold_cust']=new_gold_cust_test
x_test['new_timezone']=new_timezone_test
x_train['new_airline']=new_airline_train
x_train['new_gold_cust']=new_gold_cust_train
x_train['new_timezone']=new_timezone_train

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test_not_actual, y_train, y_test_not_actual =train_test_split(x_train,y_categories)

In [84]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test_not_actual)
from  sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test_not_actual,y_pred))
print(confusion_matrix(y_test_not_actual,y_pred))

             precision    recall  f1-score   support

   negative       0.80      0.88      0.84      1698
    neutral       0.54      0.47      0.51       575
   positive       0.69      0.55      0.61       473

avg / total       0.73      0.74      0.73      2746

[[1496  138   64]
 [ 252  273   50]
 [ 121   94  258]]

In [85]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test_not_actual)
print("Logistic Regression.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))

Logistic Regression.................................
             precision    recall  f1-score   support

   negative       0.84      0.89      0.86      1698
    neutral       0.61      0.58      0.60       575
   positive       0.79      0.66      0.72       473

avg / total       0.78      0.78      0.78      2746

[[1508  146   44]
 [ 198  336   41]
 [  92   70  311]]

In [0]:
clf = SVC(kernel = 'linear')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test_not_actual)
print("SVM.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))

In [0]:
x_axis = []
y_axis = []
for i in range(1, 26, 2):
  clf = KNeighborsClassifier(n_neighbors = i)
  score = cross_val_score(clf, x_train, y_train)
  x_axis.append(i)
  y_axis.append(score.mean())
max_score=(max(y_axis))
for i in range(len(y_axis)):
  if y_axis[i]==max_score:
      val=x_axis[i]
neigh=KNeighborsClassifier(n_neighbors = val)
neigh.fit(x_train, y_train)
y_pred = neigh.predict(x_test_not_actual)
print("KNN.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))

In [69]:
deci=DecisionTreeClassifier()
deci.fit(x_train,y_train)
y_pred = deci.predict(x_test_not_actual)
print("Decision Tree............................")
print(classification_report(y_test_not_actual,y_pred))
print(confusion_matrix(y_test_not_actual,y_pred))

Decision Tree............................
             precision    recall  f1-score   support

   negative       0.65      0.95      0.77      1740
    neutral       0.39      0.11      0.17       555
   positive       0.22      0.03      0.06       451

avg / total       0.53      0.63      0.53      2746

[[1649   52   39]
 [ 483   59   13]
 [ 395   41   15]]

In [0]:
y_final_1=rf.predict(x_test)
y_final_2=lr.predict(x_test)
y_final_3=clf.predict(x_test)
y_final_4=neigh.predict(x_test)
y_final_5=deci.predict(x_test)

In [0]:

with open('submission_1.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_1)):
      spamwriter.writerow(y_final_1[i])

with open('submission_2.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_2)):
      spamwriter.writerow(y_final_2[i])

with open('submission_3.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_3)):
      spamwriter.writerow(y_final_3[i])

with open('submission_4.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_4)):
      spamwriter.writerow(y_final_4[i])


with open('submission_5.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_5)):
      spamwriter.writerow(y_final_5[i])

files.download('submission_1.csv')
files.download('submission_2.csv')
files.download('submission_3.csv')
files.download('submission_4.csv')
files.download('submission_5.csv')